config/routes.rb
Rails.application.routes.draw do

  get 'ask', to: 'coaching#ask'

  get 'answer', to: 'coaching#answer'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def ask
  end

  def answer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<h1>Coaching#answer</h1>
<p>Find me in app/views/coaching/answer.html.erb</p>

<form action="answer" method="get">
  <input type="text" name="query">
  <input type="submit">
</form>

app/views/coaching/ask.html.erb
<h1>Coaching#ask</h1>
<p>Find me in app/views/coaching/ask.html.erb</p>

<form action="ask">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="query" placeholder="what time is it?">
  <input type="submit" value="Go on!">
</form>

<%= link_to "Check the answer page out!" , answer_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStupidCoaching</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>